//
// Created by martin on 09-05-2024.
//

#ifndef LAGRANGIAN_FLUID_SIMULATION_CONSTS_H
#define LAGRANGIAN_FLUID_SIMULATION_CONSTS_H

#define FIELD_WIDTH 100.0f
#define FIELD_HEIGHT 100.0f
#define FIELD_DEPTH 50.0f

#define NUM_PARTICLES 10000

#define TIME_STEP_IN_SECONDS 10
extern float global_time_in_step;

#endif //LAGRANGIAN_FLUID_SIMULATION_CONSTS_H
