//
// Created by martin on 09-05-2024.
//

#ifndef LAGRANGIAN_FLUID_SIMULATION_CONSTS_H
#define LAGRANGIAN_FLUID_SIMULATION_CONSTS_H

#define FIELD_WIDTH 100.0f
#define FIELD_HEIGHT 100.0f
#define FIELD_DEPTH 20.0f

#endif //LAGRANGIAN_FLUID_SIMULATION_CONSTS_H
